name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        env:
            COMPOSER_HOME: ./.composer

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup
                run: mkdir -p "$COMPOSER_HOME"

            -   name: Lint
                run: make lint
